// automatically generated by the FlatBuffers compiler, do not modify

package com.hirain.hirain.flaterbuffers;

public final class CarMode {
  private CarMode() { }
  public static final int Normal = 0;
  public static final int Factory = 1;
  public static final int Crash = 2;
  public static final int Transport = 3;

  public static final String[] names = { "Normal", "Factory", "Crash", "Transport", };

  public static String name(int e) { return names[e]; }
}

