// automatically generated by the FlatBuffers compiler, do not modify

package com.hirain.hirain.flaterbuffers;

public final class Direction {
  private Direction() { }
  public static final int Up = 0;
  public static final int Down = 1;
  public static final int Left = 2;
  public static final int Right = 3;

  public static final String[] names = { "Up", "Down", "Left", "Right", };

  public static String name(int e) { return names[e]; }
}

