// automatically generated by the FlatBuffers compiler, do not modify

package com.hirain.hirain.flaterbuffers;

public final class FrontAndBack {
  private FrontAndBack() { }
  public static final int Front = 0;
  public static final int Back = 1;

  public static final String[] names = { "Front", "Back", };

  public static String name(int e) { return names[e]; }
}

