// automatically generated by the FlatBuffers compiler, do not modify

package com.hirain.hirain.flaterbuffers;

public final class Gear {
  private Gear() { }
  public static final int P = 0;
  public static final int R = 1;
  public static final int N = 2;
  public static final int D = 3;

  public static final String[] names = { "P", "R", "N", "D", };

  public static String name(int e) { return names[e]; }
}

