// automatically generated by the FlatBuffers compiler, do not modify

package com.hirain.hirain.flaterbuffers;

public final class MirrorFoldAndOpen {
  private MirrorFoldAndOpen() { }
  public static final int LeftFlod = 0;
  public static final int LeftOpen = 1;
  public static final int Rightflod = 2;
  public static final int RightOpen = 3;
  public static final int LeftAndRightFlod = 4;
  public static final int LeftAndRightOpen = 5;

  public static final String[] names = { "LeftFlod", "LeftOpen", "Rightflod", "RightOpen", "LeftAndRightFlod", "LeftAndRightOpen", };

  public static String name(int e) { return names[e]; }
}

