// automatically generated by the FlatBuffers compiler, do not modify

package com.hirain.hirain.flaterbuffers;

public final class OpenAndClose {
  private OpenAndClose() { }
  public static final int Open = 0;
  public static final int Close = 1;

  public static final String[] names = { "Open", "Close", };

  public static String name(int e) { return names[e]; }
}

