// automatically generated by the FlatBuffers compiler, do not modify

package com.hirain.hirain.flaterbuffers;

public final class OutAmblampCmd {
  private OutAmblampCmd() { }
  public static final int OFF = 0;
  public static final int Effect1 = 1;
  public static final int Effect2 = 2;
  public static final int Effect3 = 3;
  public static final int Effect4 = 4;
  public static final int Effect5 = 5;

  public static final String[] names = { "OFF", "Effect1", "Effect2", "Effect3", "Effect4", "Effect5", };

  public static String name(int e) { return names[e]; }
}

