// automatically generated by the FlatBuffers compiler, do not modify

package com.hirain.hirain.flaterbuffers;

public final class SeatPos {
  private SeatPos() { }
  public static final int POS1 = 0;
  public static final int POS2 = 1;
  public static final int POS3 = 2;

  public static final String[] names = { "POS1", "POS2", "POS3", };

  public static String name(int e) { return names[e]; }
}

