// automatically generated by the FlatBuffers compiler, do not modify

package com.hirain.hirain.flaterbuffers;

public final class SuccessfulOrFailed {
  private SuccessfulOrFailed() { }
  public static final int Successful = 0;
  public static final int Failed = 1;

  public static final String[] names = { "Successful", "Failed", };

  public static String name(int e) { return names[e]; }
}

