// automatically generated by the FlatBuffers compiler, do not modify

package com.hirain.hirain.flaterbuffers;

public final class TurnLight {
  private TurnLight() { }
  public static final int OFF = 0;
  public static final int Left = 1;
  public static final int Right = 2;
  public static final int LeftAndRight = 3;

  public static final String[] names = { "OFF", "Left", "Right", "LeftAndRight", };

  public static String name(int e) { return names[e]; }
}

