// automatically generated by the FlatBuffers compiler, do not modify

package com.hirain.hirain.flaterbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class VehSpd extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VehSpd __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float speed() { return bb.getFloat(bb_pos + 0); }

  public static int createVehSpd(FlatBufferBuilder builder, float speed) {
    builder.prep(4, 4);
    builder.putFloat(speed);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VehSpd get(int j) { return get(new VehSpd(), j); }
    public VehSpd get(VehSpd obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

